# These are all the commands that are used throughout this project, If you would like to change up the syntax for a certain command, you can do so here.
# Just make sure to keep all the $variables in the command somewhere as these $variables such as $target and $port and $host etc... are required.
# You can also add other custom tools here as well, just make sure to go into the corresponding lib/ file and change the command there as well.
# See this projects Documentation for more details.
commands:
  web:
    "whatwebHttpTarget": "whatweb -v -a 3 http://$target:$port | tee $reportDir/web/whatweb-$target-$port.txt"
    "whatwebHttpHost": "whatweb -v -a 3 http://$host:$port | tee $reportDir/web/whatweb-$host-$port.txt"
    "dirsearchHttpTargetBig": "python3 /opt/dirsearch/dirsearch.py -u http://$target:$port/ -e php,html,txt,asp,aspx -w /usr/share/wordlists/dirb/big.txt -t 80 -x 404,401,500,502 --plain-text-report $reportDir/web/dirsearch-big-$target-$port.log"
    "dirsearchHttpHostBig": "python3 /opt/dirsearch/dirsearch.py -u http://$host:$port/ -e php,html,txt,asp,aspx -w /usr/share/wordlists/dirb/big.txt -t 80 -x 404,401,500,502 --plain-text-report $reportDir/web/dirsearch-big-$host-$port.log"
    "dirsearchHttpTargetDict": "python3 /opt/dirsearch/dirsearch.py -u http://$target:$port/ -e php,html,txt,asp,aspx -w $pwd/wordlists/dict.txt -t 80 -x 404,401,500,502 --plain-text-report $reportDir/web/dirsearch-dict-$target-$port.log"
    "dirsearchHttpHostDict": "python3 /opt/dirsearch/dirsearch.py -u http://$host:$port/ -e php,html,txt,asp,aspx -w $pwd/wordlists/dict.txt -t 80 -x 404,401,500,502 --plain-text-report $reportDir/web/dirsearch-dict-$host-$port.log"
    "curlRobotsTarget": "curl -sSik http://$target:$port/robots.txt -m 10 -o $reportDir/web/robots-$port.txt &>/dev/null"
    "curlRobotsHost": "curl -sSik http://$host:$port/robots.txt -m 10 -o $reportDir/web/robots-$host-$port.txt &>/dev/null"
    "eyewitnessTarget": "cd /opt/EyeWitness && echo 'http://$target:$port' >eyefile.txt && ./EyeWitness.py --threads 5 --ocr --no-prompt --active-scan --all-protocols --web -f eyefile.txt -d $reportDir/web/eyewitness-$target-$port && cd - &>/dev/null"
    "eyewitnessHost": "cd /opt/EyeWitness && echo 'http://$host:$port' >eyefile.txt && ./EyeWitness.py --threads 5 --ocr --no-prompt --active-scan --all-protocols --web -f eyefile.txt -d $reportDir/web/eyewitness-$host-$port && cd - &>/dev/null"
    "wafw00fTarget": "wafw00f http://$target:$port | tee $reportDir/web/wafw00f-$target-$port.txt"
    "wafw00fHost": "wafw00f http://$host:$port | tee $reportDir/web/wafw00f-$host-$port.txt"
    "niktoTarget": "nikto -ask=no -host http://$target:$port >$reportDir/web/nikto-$target-$port.txt 2>&1 &"
    "niktoHost": "nikto -ask=no -host http://$host:$port >$reportDir/web/nikto-$host-$port.txt 2>&1 &"
    "aquatone": "cat $reportDir/aquatone/urls.txt | aquatone -ports $allWebPorts -out $reportDir/aquatone/aquatone -screenshot-timeout 40000"
  webSSL:
    "whatwebSSLTarget": "whatweb -v -a 3 https://$target:$port | tee $reportDir/webSSL/whatweb-$target-$port.txt"
    "whatwebSSLHost": "whatweb -v -a 3 https://$host:$port | tee $reportDir/webSSL/whatweb-$host-$port.txt"
    "dirsearchSSLTargetBig": "python3 /opt/dirsearch/dirsearch.py -u https://$target:$port/ -e php,html,txt,asp,aspx -w /usr/share/wordlists/dirb/big.txt -t 80 -x 404,401,500,502 --plain-text-report $reportDir/webSSL/dirsearch-big-$target-$port.log"
    "dirsearchSSLHostBig": "python3 /opt/dirsearch/dirsearch.py -u https://$host:$port/ -e php,html,txt,asp,aspx -w /usr/share/wordlists/dirb/big.txt -t 80 -x 404,401,500,502 --plain-text-report $reportDir/webSSL/dirsearch-big-$host-$port.log"
    "dirsearchSSLTargetDict": "python3 /opt/dirsearch/dirsearch.py -u https://$target:$port/ -e php,html,txt,asp,aspx -w $pwd/wordlists/dict.txt -t 80 -x 404,401,500,502 --plain-text-report $reportDir/webSSL/dirsearch-dict-$target-$port.log"
    "dirsearchSSLHostDict": "python3 /opt/dirsearch/dirsearch.py -u https://$host:$port/ -e php,html,txt,asp,aspx -w $pwd/wordlists/dict.txt -t 80 -x 404,401,500,502 --plain-text-report $reportDir/webSSL/dirsearch-dict-$host-$port.log"
    "curlRobotsSSLTarget": "curl -sSik https://$target:$port/robots.txt -m 10 -o $reportDir/webSSL/robots-$port.txt &>/dev/null"
    "curlRobotsSSLHost": "curl -sSik https://$host:$port/robots.txt -m 10 -o $reportDir/webSSL/robots-$host-$port.txt &>/dev/null"
    "eyewitnessSSLTarget": "cd /opt/EyeWitness && echo 'https://$target:$port' >eyefile.txt && ./EyeWitness.py --threads 5 --ocr --no-prompt --active-scan --all-protocols --web -f eyefile.txt -d $reportDir/webSSL/eyewitness-$target-$port && cd - &>/dev/null"
    "eyewitnessSSLHost": "cd /opt/EyeWitness && echo 'https://$host:$port' >eyefile.txt && ./EyeWitness.py --threads 5 --ocr --no-prompt --active-scan --all-protocols --web -f eyefile.txt -d $reportDir/webSSL/eyewitness-$host-$port && cd - &>/dev/null"
    "wafw00fSSLTarget": "wafw00f https://$target:$port | tee $reportDir/webSSL/wafw00f-$target-$port.txt"
    "wafw00fSSLHost": "wafw00f https://$host:$port | tee $reportDir/webSSL/wafw00f-$host-$port.txt"
    "niktoSSLTarget": "nikto -ask=no -host https://$target:$port >$reportDir/webSSL/nikto-$target-$port.txt 2>&1 &"
    "niktoSSLHost": "nikto -ask=no -host https://$host:$port >$reportDir/webSSL/nikto-$host-$port.txt 2>&1 &"
    "sslscan": "sslscan http://$target:$sslport | tee $reportDir/webSSL/sslscan-color-$target-$sslport.log"
  proxy:
    "aquatoneProxy": "cat $reportDir/aquatone/proxy-urls.txt | aquatone -ports $allWebProxyPorts -proxy http://$target:$proxyPorts -out $reportDir/aquatone/aquatone-proxy/aquatone_report.html -screenshot-timeout 40000"
    "proxychainsNmapTopPorts": "proxychains nmap -vv -sT -Pn -sV -p $topTcpPorts -oA $reportDir/proxychain-top-ports 127.0.0.1"
    "proxychainsDiscoveredPorts": "proxychains nmap -vv -sT -Pn -sC -sV -p $openTcpProxyPorts --script-timeout 2m -oA $nmapReportDir/proxychain-ServiceScan 127.0.0.1"
  ssh:
    "ssh_user_enum": "python $pwd/scripts/ssh_user_enum.py --port $port --userList $pwd/wordlists/usernames.txt $target --outputFile $reportDir/ssh/ssh-usernames.json --outputFormat json"
    "patator_ssh_auto": "patator ssh_login host=$target port=$port user=$user password=FILE0 0=$pwd/wordlists/probable-v2-top1575.txt persistent=0 -l $reportDir/ssh/patatorBrute-$user -x free=user:code=0 -x ignore:mesg='Authentication failed.'"
    "patator_ssh_cewl_auto": "patator ssh_login host=$target port=$port user=$user password=FILE0 0=$reportDir/wordlists/all.txt persistent=0 -l $reportDir/ssh/patatorBrute-$user -x free=user:code=0 -x ignore:mesg='Authentication failed.'"
    "patator_ssh_single_user_custom": "patator ssh_login host=$target port=$port user=$user password=FILE0 0=$wordlist persistent=0 -l $reportDir/ssh/patatorBrute-$user -x free=user:code=0 -x ignore:mesg='Authentication failed.'"
    "patator_ssh_multiple_users_custom": "patator ssh_login host=$target port=$port user=FILE0 0=$users password=FILE1 1=$wordlist persistent=0 -l $reportDir/ssh/patatorBrute-Multiple -x free=user:code=0 -x ignore:mesg='Authentication failed.'"
  dns:
    "dnsenum": "dnsenum --dnsserver $target --enum -f $wordlist -r $hosts | tee $reportDir/dns/dnsenum-$target.log"
    "dnsDig": "dig -x $target @$target | tee $reportDir/dns/dig-$target.log"
    "dnsDigAxfr": "dig axfr @$target $alldns | tee $reportDir/dns/dig-axfr-$target.log"
# These are all the Paths that are used throughout this entire project
paths:
  "reportDir": "$reportDir"
  "pwd": "$pwd"
  "reportGlob": "$reportDir/*"
  web:
    "dsBig": "$reportDir/web/dirsearch-big-$port.log"
    "webDir": "$reportDir/web"
    "eyewitnessDirHost": "$reportDir/web/eyewitness-$hostname-$port"
    "eyewitnessDirTarget": "$reportDir/web/eyewitness-$target-$port"
    "eyewitnessDirPT": "$reportDir/proxy/web/eyewitness-$target"
    "webWhatweb": "$reportDir/web/whatweb"
    "webNikto": "$reportDir/web/niktoscan"
    "webDs": "$reportDir/web/dirsearch"
    "webDsB": "$reportDir/web/dirsearch-big"
    "webRobots": "$reportDir/web/robots"
    "webWafw00f": "$reportDir/web/wafw00f"
    "webDirsearchF": "$reportDir/web/dirsearch-foreign"
    "webDirsearchRF": "$reportDir/web/dirsearch-raftfiles"
    "webDirsearchRLD": "$reportDir/web/dirsearch-raftlargedirs"
    "webDirsearchDLM": "$reportDir/web/dirsearch-dlistmedium"
    "webWPScan": "$reportDir/web/wpscan"
    "webWPBrute": "$reportDir/web/wordpressBrute.sh"
    "wfuzzReport": "$reportDir/web/wfuzz-domain.txt"
    "weblinks": "$reportDir/web/links.txt"
    "sourceComments": "$reportDir/web/source_comments.txt"
    "aquatoneDir": "$reportDir/aquatone"
    "aquatoneReport": "$reportDir/aquatone/aquatone/aquatone_report.html"
    "aquatoneDirUrls": "$reportDir/aquatone/urls.txt"
    "aquatoneDirAq": "$reportDir/aquatone/aquatone"
  webSSL:
    "eyewitnessSSLDir": "$reportDir/webSSL/eyewitness"
    "webSSLDir": "$reportDir/webSSL"
    "webSSLScanTarget": "$reportDir/webSSL/sslscan-color-$target-$sslport.log"
    "webSSLWhatWebT": "$reportDir/webSSL/whatweb-$target"
    "webSSLWhatWeb": "$reportDir/webSSL/whatweb"
    "webSSLNiktoT": "$reportDir/webSSL/whatweb-$target"
    "webSSLNikto": "$reportDir/webSSL/whatweb-$sslport.txt"
    "webSSLwafw00fT": "$reportDir/webSSL/wafw00f-$target-$sslport.txt"
    "webSSLwafw00f": "$reportDir/webSSL/wafw00f"
    "webSSLRobotsT": "$reportDir/webSSL/robots-$target-$sslport.txt"
    "webSSLRobots": "$reportDir/webSSL/robots"
    "webSSLDirsearchT": "$reportDir/webSSL/dirsearch-$target-$sslport.log"
    "webSSLDirsearchFT": "$reportDir/webSSL/dirsearch-foreign-$target"
    "webSSLDirsearchF": "$reportDir/webSSL/dirsearch-foreign"
    "webSSLDirsearchRFT": "$reportDir/webSSL/dirsearch-raftfiles-$target"
    "webSSLDirsearchRF": "$reportDir/webSSL/dirsearch-raftfiles"
    "webSSLDirsearchRLDT": "$reportDir/webSSL/dirsearch-raftlargedirs-$target"
    "webSSLDirsearchRLD": "$reportDir/webSSL/dirsearch-raftlargedirs"
    "webSSLDirsearchDLMT": "$reportDir/webSSL/dirsearch-dlistmedium-$target"
    "webSSLDirsearchDLM": "$reportDir/webSSL/dirsearch-dlistmedium"
    "webSSLDirsearchBigT": "$reportDir/webSSL/dirsearch-big-$target-$sslport.log"
    "webSSLDirsearch": "$reportDir/webSSL/dirsearch-$host-$sslport.log"
    "webSSLDirsearchBig": "$reportDir/webSSL/dirsearch-big-$host-$sslport.log"
    "webSSLDirsearchPT": "$reportDir/proxy/webSSL/dirsearch-127.0.0.1"
    "webSSLDirsearchPTB": "$reportDir/proxy/webSSL/dirsearch-127.0.0.1-big"

  nmap:
    "nmapDir": "$nmapReportDir"
    "nmap_top_ports_xml": "$nmapReportDir/top-ports-$target.xml"
    "top_ports": "$nmapReportDir/top-ports-$target"
    "nmap_top_ports_nmap": "$nmapReportDir/top-ports-$target.nmap"
    "nmap_full_tcp_xml": "$nmapReportDir/full-tcp-scan-$target.xml"
    "full_tcp": "$nmapReportDir/full-tcp-scan-$target"
    "vulners": "$nmapReportDir/vulnscan-$target"
    "top_udp_ports": "$nmapReportDir/top-udp-ports"
    "nmap_proxychain_top_ports": "$nmapReportDir/proxychain-top-ports.xml"
    "nmap_top_udp_ports_xml": "$nmapReportDir/top-udp-ports.xml"
    "nmapCups": "$nmapReportDir/cups-enum"
    "nmapJavaRmi": "$nmapReportDir/java-rmi"
    "nmapJavaRmiDump": "$nmapReportDir/java-rmi-dump"
    "nmapVNC": "$nmapReportDir/vnc"
    "nmapTelnet": "$nmapReportDir/telnet"
    "nmapCassandra": "$nmapReportDir/cassandra"
    "nmapMySQL": "$nmapReportDir/mySql"
    "nmapMsSQL": "$nmapReportDir/msSql"
    "nmapMongo": "$nmapReportDir/mongo"
    "nmapPop3": "$nmapReportDir/pop3"
    "nmapKerberos": "$nmapReportDir/kerberos"
  proxy:
    "aquatoneProxyReport": "$reportDir/aquatone/aquatone-proxy/aquatone_report.html"
    "aquatoneDirProxyUrls": "$reportDir/aquatone/proxy-urls.txt"
    "aquatoneDirProxy": "$reportDir/aquatone/aquatone-proxy"
    "proxychain_top_ports": "$nmapReportDir/proxychain-top-ports"
    "proxychain_serviceScan": "$nmapReportDir/proxychain-ServiceScan"
    "proxyGlob": "$reportDir/proxy/*"
    "reportGlobWebSSL": "$reportDir/webSSL/*"
    "proxyDir": "$reportDir/proxy"
    "proxyWebSSL": "$reportDir/proxy/webSSL"
    "proxyWeb": "$reportDir/proxy/web"
    "proxyDns": "$reportDir/proxy/dns"
    "proxyOracle": "$reportDir/proxy/oracle"
    "proxyVulns": "$reportDir/proxy/vulns"
    "webWhatwebProxy": "$reportDir/proxy/web/whatweb-proxy"
    "webDsP": "$reportDir/proxy/web/dirsearch-127.0.0.1-proxy"
    "webDsPB": "$reportDir/proxy/web/dirsearch-127.0.0.1-proxy-big"
    "webNiktoP": "$reportDir/proxy/web/nikto-port"
    "webWhatwebPT": "$reportDir/proxy/web/whatweb-proxy-$target"
  dns:
    "dnsDir": "$reportDir/dns"
    "dnsZoneXfer": "$reportDir/dns/dig-axfr-$target.log"
    "dnsDig": "$reportDir/dns/dig-$target.log"
    "dnsEnum": "$reportDir/dns/dnsenum-$target.log"
    "falsePosWordlist": "$pwd/wordlists/testFalsePositives.txt"
  rpc:
    "rpcDir": "$reportDir/rpc"
    "impRpc": "$reportDir/rpc/rpcdump.log"
    "rpcEnum4linux": "$reportDir/rpc/rpcEnum4linux.log"
    "rpcDir": "$reportDir/rpc"
  vuln:
    "vulnDir": "$reportDir/vulns"
    "ftp_vulns": "$reportDir/vulns/ftp.log"
    "ssh_vulns": "$reportDir/vulns/ssh.log"
    "smtp_vulns": "$reportDir/vulns/smtp.log"
    "http_vulns": "$reportDir/vulns/http-title.log"
    "all_vulns": "$reportDir/vulns/all-services.log"
  wordlists:
    "top5Ksubs": "/usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt"
    "wordlistsDir": "$reportDir/wordlists"
    "usernames_wordlist": "$pwd/wordlists/usernames.txt"
    "Big": "/usr/share/wordlists/dirb/big.txt"
    "dlistMed": "/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt"
    "raftLarge": "/usr/share/seclists/Discovery/Web-Content/raft-large-files-lowercase.txt"
    "raftLd": "/usr/share/seclists/Discovery/Web-Content/raft-large-directories.txt"
    "CewlPlus": "$reportDir/wordlists/all.txt"
    "CustomPass1575": "$pwd/wordlists/probable-v2-top1575.txt"
    "probPass1575": "/usr/share/seclists/Passwords/probable-v2-top1575.txt"
    "wlDict": "$pwd/wordlists/dict.txt"
  nfs:
    "nfsDir": "$reportDir/nfs"
    "nmapNfs": "$nmapReportDir/nfs"
    "nfs_showmount": "$reportDir/nfs/nfs-show-mount.txt"
  sip:
    "sipDir": "$reportDir/sip"
    "nmapSip": "$nmapReportDir/sip"
    "svWar": "$reportDir/sip/svwar.txt"
  smtp:
    "smtpDir": "$reportDir/smtp"
    "smtp_user_enum": "$reportDir/smtp/smtp-user-enum-port"
  smb:
    "nmapSmb": "$nmapReportDir/smbvulns-$target"
    "smbDir": "$reportDir/smb"
    "smbScan": "$reportDir/smb/smb-scan-$target.log"
  ssh:
    "sshDir": "$reportDir/ssh"
    "ssh_user_enum": "$pwd/scripts/ssh_user_enum.py"
    "ssh_usernames": "$reportDir/ssh/ssh-usernames.json"
  snmp:
    "snmpDir": "$reportDir/snmp"
    "snmpwalk_log": "$reportDir/snmp/snmpwalk.log"
    "snmpcheck_log": "$reportDir/snmp/snmp-check.log"
    "snmp_onesixtyone_log": "$reportDir/snmp/onesixtyone.log"
  ldap:
    "ldapDir": "$reportDir/ldap"
    "ldapEnum4linux": "$reportDir/ldap/ldapenum4linux.txt"
    "nmapLdap": "$nmapReportDir/ldap"
  oracle:
    "oracleDir": "$reportDir/oracle"
    "oraclelog": "$reportDir/oracle/oracle.log"
    "oracletxt": "$reportDir/oracle/oracle.txt"
    "oraclesid": "$reportDir/oracle/oracle-sid.txt"
    "nmaporacle": "$nmapReportDir/oracle"
    "oracleBrute": "$pwd/lib/oracle.sh"
  ftp:
    "nmap_ftp": "$nmapReportDir/ftp-enum"
